#!/usr/bin/perl

# I want to type in times in a terminal window (or paste) and have mpv seek to that time immediately. 
# this program reads line after line, and tells the mpv window that it opens, to seek to that time. 
# doesn't give any great error message if mpv exits for a dumb reason
# also should stop the terminal part if mpv quite

# copyright 2021 kanliot@github
# https://perldoc.perl.org/perlartistic for license


use strict;
use 5.10.0; # for say

my $fifo='/tmp/mpvreadtime';
system 'mkfifo',$fifo;
END { unlink $fifo }


# bleah this killing stuff is buggy as i write it, the main thing is to kill the readline when mpv is closed. 
# so just have the parent of the mpv process kill it's parent, that's it. 
# honestly i don't know how to have the child kill the parent of the parent and the parent kill the child and it's child and so on and so on


my $pid;
if ($pid=fork) {
} else {
	if( my $id=fork){  #  get pid of mpv
		waitpid $id,0; # wait child to exit;
		kill 'KILL', getpgrp 0; # kill the readline process
		exit;
	} else {
		exec 'mpv','--force-window=yes',"--input-ipc-server=$fifo",'--no-terminal', @ARGV; 
	}
}

say 'enter times to seek to';
say 'enter q to quit';

while (<STDIN>){
	chomp;
	exit 0 if $_ eq 'q' or $_ eq 'Q';
	my $strong=$_;
	if(/:;/) {
		$strong=\to_seconds($_);
	}
# should now be in seconds
	$_ = <<"MSG";
echo '{ "command": ["set_property", "playback-time", "$strong" ] }' | socat - $fifo >/dev/null
MSG
	system 'bash','-ic',$_;
}



sub to_seconds{
	my $has_ms = scalar $_[0] =~ /\.\d+/;

        my @components = split /[;:\.]/, $_[0];
	push @components, 0 if not $has_ms ;

	@components = reverse @components;

	push @components, 0 if $#components < 3 ; # hours are opt.
	push @components, 0 if $#components < 3 ; # minutes are opt.

# now we should have an array of ms, s, min, h.

     	return (($components[3] * 60 + $components[2]) * 60 + $components[1])        + ".$components[0]";
}


#       mpv can be controlled by external programs using the JSON-based IPC protocol.  It can be enabled by specifying the path to a unix socket or a  named  pipe  using the option --input-ipc-server. Clients can connect to this socket and send commands to the player or receive events from it.
# mpvs socket dox https://github.com/mpv-player/mpv/blob/master/DOCS/man/ipc.rst

